site_name: "NPFL067: Statistical Methods in Natural Language Processing I"
site_url: ""
use_directory_urls: false
nav:
    - Home: index.md
    - Assignment 1.1: assignment1/assignment1.md
    - Assignment 1.2_en: assignment1/assignment12.md
    - Assignment 1.2_cz: assignment1/assignment12_cz.md
    - Assignment 2: assignment2/assignment2.md
theme: readthedocs
plugins: []